name: "Report bug"
description: "Create a bug report to help this project improve"
labels: ["bug"]
body:
- type: markdown
  attributes:
      value: |
        ### Thank you for contributing to this project!
        Before create a new bug report please search and check there isn't a duplicate already present.
- type: input
  id: chip
  validations:
      required: true
  attributes:
      label: Chip
      description: Provide the chip model
      value: For example CH32X035G8U6 etc...
- type: textarea
  id: bug-description
  validations:
      required: true
  attributes:
      label: Bug description
      description: |
        Provide a description of the bug you're found.
        Please don't expect anyone to guess everything but give enough information.
- type: textarea
  id: reproduce
  attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug (when possible).
- type: textarea
  id: expected-behavior
  attributes:
      label: Expected behavior
      description: Describe what you expected to happen instead.
- type: textarea
  id: additional-info
  attributes:
      label: Additional information
      description: Add any additional information related to the issue here.
- type: textarea
  id: usage-tips
  validations:
      required: true
  attributes:
      label: Usage tips
      description: |
        Please keep this notes for other contributors
      value: |
        * Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into this.
        * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this.
        * Subscribe to receive notifications on status change and new comments, you can do also without add comment.
